name: make

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master branch
  push:
    branches:
    - master
    - '*/ci'
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install prereqs
      run: sudo apt-get install python3-proselint
      
    - name: store proselint config
      run: |
        echo '{' > .proselintrc
        echo '   "checks": {' >> .proselintrc
        echo '     "typography.diacritical_marks": false,' >> .proselintrc
        echo '     "typography.symbols": false,' >> .proselintrc
        echo '     "annotations.misc": false' >> .proselintrc
        echo '   }' >> .proselintrc
        echo '}' >> .proselintrc

    - name: check prose
      run: make check
