name: make

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master branch
  push:
    branches:
    - master
    - '*/ci'
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install prereqs
      run: sudo apt-get install proselint
      
    - name: store proselint config
      run: |
      cat <<EOF > .proselint
{
  "checks": {
    "typography.diacritical_marks": false,
    "typography.symbols": false,
    "annotations.misc": false
  }
}
EOF

    - name: check prose
      run: make check
