# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.

name: pdf
on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    branches:
      - master
    paths:
      - '**.md'

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install pandoc
        run: sudo apt-get install pandoc

      - name: build pdf
        run: make pdf
